/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_muntashirakon_crypto_spake2_Spake2Context */

#ifndef _Included_io_github_muntashirakon_crypto_spake2_Spake2Context
#define _Included_io_github_muntashirakon_crypto_spake2_Spake2Context
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_muntashirakon_crypto_spake2_Spake2Context_MAX_MSG_SIZE
#define io_github_muntashirakon_crypto_spake2_Spake2Context_MAX_MSG_SIZE 32L
#undef io_github_muntashirakon_crypto_spake2_Spake2Context_MAX_KEY_SIZE
#define io_github_muntashirakon_crypto_spake2_Spake2Context_MAX_KEY_SIZE 64L
/*
 * Class:     io_github_muntashirakon_crypto_spake2_Spake2Context
 * Method:    allocNewContext
 * Signature: (I[B[B)J
 */
JNIEXPORT jlong JNICALL Java_io_github_muntashirakon_crypto_spake2_Spake2Context_allocNewContext
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     io_github_muntashirakon_crypto_spake2_Spake2Context
 * Method:    generateMessage
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_github_muntashirakon_crypto_spake2_Spake2Context_generateMessage
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_github_muntashirakon_crypto_spake2_Spake2Context
 * Method:    processMessage
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_github_muntashirakon_crypto_spake2_Spake2Context_processMessage
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_github_muntashirakon_crypto_spake2_Spake2Context
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_muntashirakon_crypto_spake2_Spake2Context_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
